services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: titancore-backend:1.0
    container_name: titancore-backend-compose
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://178.105.30.16:5000/api
    image: titancore-frontend:1.0
    container_name: titancore-frontend-compose
    ports:
      - "3000:80"